version: "3.8"

services:
    # mongo-db:
    #   image: mongo:6.0.6
    #   restart: always
    #   environment:
    #     MONGO_INITDB_ROOT_USERNAME: mongo-user
    #     MONGO_INITDB_ROOT_PASSWORD: 123456
    #   volumes:
    #     - ./mongo:/data/db
    #   ports:
    #     - 27017:27017

    postgres-db:
        image: postgres:17.5
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        container_name: todo-list-db
        volumes:
            - ./postgres:/var/lib/postgresql/data
